name: secdart_analyzer_plugin_loader
description: This is the "loader" package for the secdart_analyzer_plugin.
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  secdart_analyzer_plugin:
    path: C:\Storage\phd\secdart\secdart_analyzer_plugin