name: secdart_analyzer
description: Provides a gradual security typing static analysis for SecDart.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analyzer: '^0.30.0'
  plugin: '^0.2.0'
  #TODO: It should be removed (we are using this to resolve the SDK)
  #code_transformers: any

dependency_overrides:
  analyzer:
    path: ../../angular_analyzer_plugin/deps/sdk/pkg/analyzer
dev_dependencies:
  test: ^0.12.0