name: secdart_analyzer
description: Provides a gradual security typing static analysis for SecDart.
version: 0.0.1

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  analyzer: '^0.31.0-alpha.1'
  plugin: '^0.2.0'

dev_dependencies:
  test_reflective_loader: "^0.1.3"
  test: ^0.12.0