name: secdart_analyzer_plugin
description: A plugin for the Dart Analyzer containing a gradual security typing static analysis.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analyzer: '^0.31.0-alpha.1'
  secdart_analyzer:
    path: ../sec_analyzer
dev_dependencies:
  test: ^0.12.0