name: secdart_server_plugin
description: A plugin for the Dart Analysis Server
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'


dependencies:
  analyzer: '>=0.25.1'
  secdart_analyzer_plugin:
    path: ../analyzer_plugin
  analysis_server:
    path: ../../angular_analyzer_plugin/deps/sdk/pkg/analysis_server
  analyzer_plugin:
    path: ../../angular_analyzer_plugin/deps/sdk/pkg/analyzer_plugin
  plugin: '^0.2.0'

dependency_overrides:
  analyzer:
     path: ../../angular_analyzer_plugin/deps/sdk/pkg/analyzer
  analysis_server:
     path: ../../angular_analyzer_plugin/deps/sdk/pkg/analysis_server
  front_end:
    path: ../../angular_analyzer_plugin/deps/sdk/pkg/front_end

dev_dependencies:
  test: ^0.12.0
