name: secdart_server_plugin
description: A plugin for the Dart Analysis Server
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'


dependencies:
  analyzer: '^0.30.0'
  secdart_analyzer_plugin:
    path: ../analyzer_plugin
  analysis_server: any
  analyzer_plugin: any
  plugin: '^0.2.0'

dependency_overrides:
  analyzer:
     path: ../deps/sdk/pkg/analyzer
  analysis_server:
     path: ../deps/sdk/pkg/analysis_server
  front_end:
    path: ../deps/sdk/pkg/front_end
  telemetry:
      path: ../deps/sdk/pkg/telemetry

dev_dependencies:
  test: ^0.12.0
