name: secdart_server_plugin
description: A plugin for the Dart Analysis Server
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'


dependencies:
  analyzer: ^0.31.0-alpha.1
  secdart_analyzer_plugin:
    path: ../analyzer_plugin
  analysis_server: any
  analyzer_plugin: any
  front_end: any
  plugin: '^0.2.0'

dev_dependencies:
  test: ^0.12.0
